### ISSUE TITLE
Name spelled wrong

### ISSUE THREAD

**Issue by ghost** [TruncatedDinoSour/armour#1]
This repository name is spelled wrong! It's supposed to be "armor", not "armour"! My browser even highlights "armour" as wrong. Very silly mistake IMO and should be fixed as soon as possible.

**Comment by ar1ja** [comment]
Armor on pypi was taken, https://pypi.org/project/armor/ + I want to do British English anyway.

**Comment by ghost** [comment]
> Armor on pypi was taken, https://pypi.org/project/armor/ + I want to do British English anyway.

shut up
